toml
    [build]
      # Esta línea le dice a Netlify dónde encontrar tus funciones
      functions = "netlify/functions"

    [[redirects]]
      # Esta regla es para que la URL /thanks-funding funcione sin el .html
      from = "/thanks-funding"
      to = "/thanks-funding.html"
      status = 200